[package]
name = "crochet-core"
version = "0.1.0"
edition = "2021"

[dependencies]
crochet-types = { path = "../crochet-types" }
rand = { version = "0.8", features = ["getrandom"] }
rand_chacha = "0.3"
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
approx = "0.5"
